export const sampleInternships = [
  // --- IT & Software ---
  { id: 1, title: 'Frontend Developer Intern (React)', company_name: 'Innovate Solutions Inc.', location: 'Bengaluru, Karnataka', work_mode: 'Hybrid', deadline: '2025-10-31T23:59:59Z', start_date: '2025-11-15T09:00:00Z', description: 'Build cutting-edge UIs with React, working closely with senior developers and designers.', must_have_skills: ['HTML', 'CSS', 'JavaScript', 'React', 'Git'], good_to_have_skills: ['TypeScript', 'Redux'], status: 'approved' },
  { id: 2, title: 'Backend Developer Intern (Node.js)', company_name: 'Tech Systems Co.', location: 'Pune, Maharashtra', work_mode: 'Remote', deadline: '2025-11-05T23:59:59Z', start_date: '2025-11-20T09:00:00Z', description: 'Develop and maintain server-side logic, build robust APIs, and ensure high performance.', must_have_skills: ['Node.js', 'Express', 'MongoDB', 'REST APIs'], good_to_have_skills: ['Docker', 'AWS'], status: 'approved' },
  { id: 3, title: 'Data Science Intern', company_name: 'Data Insights Ltd.', location: 'Hyderabad, Telangana', work_mode: 'On-site', deadline: '2025-10-25T23:59:59Z', start_date: '2025-11-10T09:00:00Z', description: 'Focus on data analysis, machine learning model creation, and generating actionable insights.', must_have_skills: ['Python', 'Pandas', 'NumPy', 'SQL'], good_to_have_skills: ['Scikit-learn', 'TensorFlow'], status: 'approved' },
  { id: 4, title: 'Cloud Engineer Intern (Azure)', company_name: 'InfraCloud Solutions', location: 'Chennai, Tamil Nadu', work_mode: 'Hybrid', deadline: '2025-11-15T23:59:59Z', start_date: '2025-12-01T09:00:00Z', description: 'Learn to build and manage scalable cloud infrastructure on Microsoft Azure.', must_have_skills: ['Azure', 'PowerShell', 'Networking Basics'], good_to_have_skills: ['Terraform', 'Kubernetes'], status: 'approved' },
  { id: 5, title: 'Mobile App Developer Intern (Flutter)', company_name: 'Appify Creations', location: 'Kochi, Kerala', work_mode: 'Remote', deadline: '2025-11-20T23:59:59Z', start_date: '2025-12-05T09:00:00Z', description: 'Develop cross-platform mobile applications using Flutter for Android and iOS.', must_have_skills: ['Flutter', 'Dart', 'Mobile UI Design'], good_to_have_skills: ['Firebase', 'State Management'], status: 'approved' },
  { id: 6, title: 'Cybersecurity Analyst Intern', company_name: 'SecureNet', location: 'Delhi', work_mode: 'On-site', deadline: '2025-11-30T23:59:59Z', start_date: '2025-12-15T09:00:00Z', description: 'Join our SOC to monitor for threats, analyze security alerts, and assist in incident response.', must_have_skills: ['Networking', 'Operating Systems', 'Security Principles'], good_to_have_skills: ['Wireshark', 'SIEM'], status: 'approved' },
  { id: 7, title: 'DevOps Intern', company_name: 'DeployFast', location: 'Bengaluru, Karnataka', work_mode: 'Hybrid', deadline: '2025-12-01T23:59:59Z', start_date: '2025-12-15T09:00:00Z', description: 'Work on CI/CD pipelines, containerization with Docker, and orchestration with Kubernetes.', must_have_skills: ['Linux', 'Git', 'Docker', 'CI/CD Concepts'], good_to_have_skills: ['Kubernetes', 'Jenkins'], status: 'approved' },
  { id: 8, title: 'AI/ML Engineer Intern', company_name: 'Cognitive AI', location: 'Bengaluru, Karnataka', work_mode: 'Remote', deadline: '2025-12-15T23:59:59Z', start_date: '2026-01-10T09:00:00Z', description: 'Work on real-world machine learning projects, from data preprocessing to model deployment.', must_have_skills: ['Python', 'TensorFlow or PyTorch', 'ML Concepts'], good_to_have_skills: ['NLP', 'Computer Vision'], status: 'approved' },
  { id: 9, title: 'Quality Assurance Intern', company_name: 'BugFinders Inc.', location: 'Pune, Maharashtra', work_mode: 'Hybrid', deadline: '2025-11-22T23:59:59Z', start_date: '2025-12-08T09:00:00Z', description: 'Perform manual testing of web applications, create test cases, and report bugs.', must_have_skills: ['Manual Testing', 'Test Case Writing', 'JIRA'], good_to_have_skills: ['Selenium Basics', 'SQL'], status: 'approved' },
  
  // --- Design & Creative ---
  { id: 10, title: 'UI/UX Design Intern', company_name: 'Creative Minds Studio', location: 'Mumbai, Maharashtra', work_mode: 'Hybrid', deadline: '2025-12-01T23:59:59Z', start_date: '2026-01-05T09:00:00Z', description: 'Design intuitive user experiences through wireframing, prototyping, and user research.', must_have_skills: ['Figma', 'Sketch', 'Wireframing', 'Prototyping'], good_to_have_skills: ['Adobe XD', 'User Research'], status: 'approved' },
  { id: 11, title: 'Graphic Design Intern', company_name: 'Pixel Perfect Studios', location: 'Remote', work_mode: 'Remote', deadline: '2025-12-05T23:59:59Z', start_date: '2025-12-20T09:00:00Z', description: 'Create visual concepts for websites, social media, and marketing materials.', must_have_skills: ['Adobe Photoshop', 'Adobe Illustrator', 'Creativity'], good_to_have_skills: ['InDesign', 'After Effects'], status: 'approved' },
  { id: 12, title: 'Architectural Design Intern', company_name: 'Urban Blueprints', location: 'Pune, Maharashtra', work_mode: 'On-site', deadline: '2025-12-10T23:59:59Z', start_date: '2026-01-05T09:00:00Z', description: 'Develop architectural designs, prepare drawings, and create 3D models of buildings.', must_have_skills: ['Revit', 'SketchUp', 'Architectural Drawing'], good_to_have_skills: ['AutoCAD 3D', 'Photoshop'], status: 'approved' },

  // --- Business & Management ---
  { id: 13, title: 'Product Management Intern', company_name: 'NextGen Products', location: 'Noida, Uttar Pradesh', work_mode: 'On-site', deadline: '2025-11-10T23:59:59Z', start_date: '2025-11-25T09:00:00Z', description: 'Define product roadmaps, write specifications, and analyze user feedback.', must_have_skills: ['Market Research', 'Agile Methodologies', 'Communication'], good_to_have_skills: ['JIRA', 'Roadmapping'], status: 'approved' },
  { id: 14, title: 'Business Analyst Intern', company_name: 'Strategy First Consulting', location: 'Gurugram, Haryana', work_mode: 'Hybrid', deadline: '2025-10-20T23:59:59Z', start_date: '2025-11-01T09:00:00Z', description: 'Bridge the gap between business and technology by gathering requirements and documenting needs.', must_have_skills: ['Requirement Gathering', 'MS Excel', 'Analytical Skills'], good_to_have_skills: ['SQL', 'Power BI'], status: 'approved' },
  { id: 15, title: 'Digital Marketing Intern', company_name: 'Growth Hackers', location: 'Remote', work_mode: 'Remote', deadline: '2025-10-28T23:59:59Z', start_date: '2025-11-05T09:00:00Z', description: 'Support marketing team in creating and executing digital campaigns across various channels.', must_have_skills: ['Social Media Marketing', 'Content Creation', 'SEO Basics'], good_to_have_skills: ['Google Analytics', 'Email Marketing'], status: 'approved' },
  { id: 16, title: 'Finance & Accounting Intern', company_name: 'Capital Advisors LLP', location: 'Mumbai, Maharashtra', work_mode: 'Hybrid', deadline: '2025-11-25T23:59:59Z', start_date: '2025-12-10T09:00:00Z', description: 'Support the finance team with financial reporting, budget analysis, and statement preparation.', must_have_skills: ['MS Excel', 'Accounting Principles', 'Financial Modeling'], good_to_have_skills: ['Tally ERP', 'QuickBooks'], status: 'approved' },
  { id: 17, title: 'Human Resources Intern', company_name: 'People First Corp', location: 'Delhi', work_mode: 'On-site', deadline: '2025-11-15T23:59:59Z', start_date: '2025-12-01T09:00:00Z', description: 'Assist with recruitment, onboarding, employee engagement, and maintaining HR records.', must_have_skills: ['Communication', 'MS Office', 'Interpersonal Skills'], good_to_have_skills: ['Recruitment Software', 'HR Policies'], status: 'approved' },
  { id: 18, title: 'Business Development Intern', company_name: 'GrowthLeap', location: 'Noida, Uttar Pradesh', work_mode: 'Hybrid', deadline: '2025-11-18T23:59:59Z', start_date: '2025-12-02T09:00:00Z', description: 'Focus on generating leads, qualifying prospects, and supporting the sales team.', must_have_skills: ['Lead Generation', 'Communication', 'MS Office'], good_to_have_skills: ['CRM Software', 'Negotiation'], status: 'approved' },
  { id: 19, title: 'Supply Chain Management Intern', company_name: 'LogiTrack Solutions', location: 'Chennai, Tamil Nadu', work_mode: 'On-site', deadline: '2025-11-28T23:59:59Z', start_date: '2025-12-12T09:00:00Z', description: 'Learn the fundamentals of logistics, inventory management, and shipment tracking.', must_have_skills: ['Inventory Management', 'MS Excel', 'Analytical Skills'], good_to_have_skills: ['SAP', 'Logistics Software'], status: 'approved' },

  // --- Core Engineering ---
  { id: 20, title: 'Mechanical Engineering Intern', company_name: 'Precision Motors Ltd.', location: 'Chennai, Tamil Nadu', work_mode: 'On-site', deadline: '2025-11-10T23:59:59Z', start_date: '2025-12-01T09:00:00Z', description: 'Assist in the design, development, and testing of mechanical components and systems.', must_have_skills: ['AutoCAD', 'SolidWorks', 'Engineering Mechanics'], good_to_have_skills: ['ANSYS', 'CATIA'], status: 'approved' },
  { id: 21, title: 'Civil Engineering Site Intern', company_name: 'InfraBuilders Pvt. Ltd.', location: 'Hyderabad, Telangana', work_mode: 'On-site', deadline: '2025-11-05T23:59:59Z', start_date: '2025-11-20T09:00:00Z', description: 'Gain experience in on-site construction management, quality control, and site supervision.', must_have_skills: ['Site Supervision', 'AutoCAD', 'Building Materials'], good_to_have_skills: ['Primavera P6', 'Surveying'], status: 'approved' },
  { id: 22, title: 'Electrical Engineering Intern', company_name: 'PowerGrid Solutions', location: 'Kolkata, West Bengal', work_mode: 'On-site', deadline: '2025-11-20T23:59:59Z', start_date: '2025-12-05T09:00:00Z', description: 'Assist in the design and analysis of electrical systems related to power distribution.', must_have_skills: ['Circuit Analysis', 'MATLAB', 'Electrical Schematics'], good_to_have_skills: ['PLC Programming', 'Power Systems'], status: 'approved' },
  { id: 23, title: 'Automotive Engineering Intern', company_name: 'AutoDrive Dynamics', location: 'Pune, Maharashtra', work_mode: 'On-site', deadline: '2025-12-10T23:59:59Z', start_date: '2026-01-02T09:00:00Z', description: 'Work on vehicle dynamics, powertrain systems, and component testing in the automotive sector.', must_have_skills: ['Automotive Systems', 'CATIA', 'Thermodynamics'], good_to_have_skills: ['MATLAB/Simulink', 'Vehicle Testing'], status: 'approved' },
  { id: 24, title: 'Aerospace Engineering Intern', company_name: 'AeroSpace Innovations', location: 'Bengaluru, Karnataka', work_mode: 'On-site', deadline: '2025-12-20T23:59:59Z', start_date: '2026-01-15T09:00:00Z', description: 'Contribute to projects in aerodynamics, structural analysis, and propulsion systems.', must_have_skills: ['Aerodynamics', 'CFD', 'Structural Analysis'], good_to_have_skills: ['ANSYS', 'MATLAB'], status: 'approved' },
  { id: 25, title: 'Chemical Engineering Intern', company_name: 'ChemProcess Solutions', location: 'Ahmedabad, Gujarat', work_mode: 'On-site', deadline: '2025-11-30T23:59:59Z', start_date: '2025-12-15T09:00:00Z', description: 'Assist with process design, optimization, and safety compliance in a chemical plant.', must_have_skills: ['Process Simulation', 'Mass Transfer', 'Thermodynamics'], good_to_have_skills: ['Aspen HYSYS', 'Plant Safety'], status: 'approved' },

  // --- Media & Content ---
  { id: 26, title: 'Content Writer Intern', company_name: 'WordWeavers Agency', location: 'Remote', work_mode: 'Remote', deadline: '2025-11-30T23:59:59Z', start_date: '2025-12-15T09:00:00Z', description: 'Create engaging and SEO-friendly content for blogs, websites, and social media.', must_have_skills: ['Excellent Writing', 'SEO Writing', 'Content Editing'], good_to_have_skills: ['WordPress', 'Grammarly'], status: 'approved' },
  { id: 27, title: 'Journalism Intern', company_name: 'The Daily Chronicle', location: 'Delhi', work_mode: 'Hybrid', deadline: '2025-11-25T23:59:59Z', start_date: '2025-12-10T09:00:00Z', description: 'Assist reporters with research, interviews, and writing articles for print and digital platforms.', must_have_skills: ['Reporting', 'Interviewing', 'AP Style'], good_to_have_skills: ['Fact-Checking', 'Digital Media'], status: 'approved' },
  { id: 28, title: 'Video Production Intern', company_name: 'Motion Flix', location: 'Mumbai, Maharashtra', work_mode: 'On-site', deadline: '2025-12-05T23:59:59Z', start_date: '2025-12-20T09:00:00Z', description: 'Assist with all stages of video production, including shooting, editing, and post-production.', must_have_skills: ['Video Shooting', 'Adobe Premiere Pro', 'Storyboarding'], good_to_have_skills: ['After Effects', 'Lighting'], status: 'approved' },

  // --- Science & Healthcare ---
  { id: 29, title: 'Biotechnology Research Intern', company_name: 'GeneLife Sciences', location: 'Hyderabad, Telangana', work_mode: 'On-site', deadline: '2025-11-20T23:59:59Z', start_date: '2025-12-05T09:00:00Z', description: 'Assist researchers in a laboratory setting with experiments, data collection, and analysis.', must_have_skills: ['PCR', 'Cell Culture', 'Lab Techniques'], good_to_have_skills: ['ELISA', 'Data Analysis'], status: 'approved' },
  { id: 30, title: 'Pharmaceutical Science Intern', company_name: 'PharmaCure Labs', location: 'Ahmedabad, Gujarat', work_mode: 'On-site', deadline: '2025-11-15T23:59:59Z', start_date: '2025-12-01T09:00:00Z', description: 'Support the R&D team in formulation development and quality control processes.', must_have_skills: ['Quality Control', 'Formulation', 'HPLC'], good_to_have_skills: ['Regulatory Affairs', 'Documentation'], status: 'approved' },
  { id: 31, title: 'Clinical Research Intern', company_name: 'MedTrials Connect', location: 'Delhi', work_mode: 'Hybrid', deadline: '2025-12-01T23:59:59Z', start_date: '2025-12-15T09:00:00Z', description: 'Assist with clinical trial coordination, data management, and ensuring regulatory compliance.', must_have_skills: ['Clinical Research', 'Data Management', 'GCP'], good_to_have_skills: ['Medical Terminology', 'Ethics'], status: 'approved' },
  { id: 32, title: 'Environmental Science Intern', company_name: 'Green Earth Foundation', location: 'Pune, Maharashtra', work_mode: 'Hybrid', deadline: '2025-11-10T23:59:59Z', start_date: '2025-11-25T09:00:00Z', description: 'Work on projects related to environmental impact assessment, conservation, and sustainability.', must_have_skills: ['Environmental Science', 'Data Collection', 'Report Writing'], good_to_have_skills: ['GIS Software', 'Field Work'], status: 'approved' },

  // --- Other Sectors ---
  { id: 33, title: 'Legal Intern', company_name: 'Veritas Legal Associates', location: 'Delhi', work_mode: 'On-site', deadline: '2025-11-12T23:59:59Z', start_date: '2025-11-28T09:00:00Z', description: 'Support lawyers with legal research, drafting documents, and preparing case files.', must_have_skills: ['Legal Research', 'Drafting', 'Case Law Analysis'], good_to_have_skills: ['Corporate Law', 'Litigation'], status: 'approved' },
  { id: 34, title: 'Hospitality Management Intern', company_name: 'Grand Palace Hotels', location: 'Jaipur, Rajasthan', work_mode: 'On-site', deadline: '2025-10-30T23:59:59Z', start_date: '2025-11-15T09:00:00Z', description: 'Experience luxury hotel operations, rotating through departments like front office and F&B.', must_have_skills: ['Guest Relations', 'Communication', 'Teamwork'], good_to_have_skills: ['Hotel Management Software', 'Event Coordination'], status: 'approved' },
  { id: 35, title: 'Education Technology (EdTech) Intern', company_name: 'LearnSphere', location: 'Remote', work_mode: 'Remote', deadline: '2025-12-10T23:59:59Z', start_date: '2026-01-02T09:00:00Z', description: 'Assist in developing and testing online learning modules and digital educational content.', must_have_skills: ['Content Development', 'Instructional Design', 'LMS'], good_to_have_skills: ['Video Editing', 'User Feedback Analysis'], status: 'approved' },
  { id: 36, title: 'Agriculture Technology Intern', company_name: 'AgroFuture', location: 'Chandigarh, Punjab', work_mode: 'Hybrid', deadline: '2025-11-20T23:59:59Z', start_date: '2025-12-05T09:00:00Z', description: 'Work on projects involving precision agriculture, drone technology, and soil health analysis.', must_have_skills: ['Agriculture Science', 'Data Analysis', 'Field Research'], good_to_have_skills: ['Drone Operation', 'GIS'], status: 'approved' },
  { id: 37, title: 'Event Management Intern', company_name: 'Grand Events Inc.', location: 'Mumbai, Maharashtra', work_mode: 'On-site', deadline: '2025-11-15T23:59:59Z', start_date: '2025-12-01T09:00:00Z', description: 'Assist in planning and executing corporate events, from vendor coordination to on-site support.', must_have_skills: ['Event Planning', 'Vendor Management', 'Organization'], good_to_have_skills: ['Budgeting', 'Marketing'], status: 'approved' },
  { id: 38, title: 'Fashion Design Intern', company_name: 'Haute Couture House', location: 'Delhi', work_mode: 'On-site', deadline: '2025-11-28T23:59:59Z', start_date: '2025-12-12T09:00:00Z', description: 'Support the design team with sketching, fabric sourcing, and creating tech packs.', must_have_skills: ['Fashion Sketching', 'Adobe Illustrator', 'Pattern Making'], good_to_have_skills: ['Textile Knowledge', 'Sewing'], status: 'approved' },
  { id: 39, title: 'Robotics Intern', company_name: 'RoboMechanics', location: 'Bengaluru, Karnataka', work_mode: 'On-site', deadline: '2025-12-05T23:59:59Z', start_date: '2025-12-20T09:00:00Z', description: 'Work on the development and programming of robotic systems for industrial automation.', must_have_skills: ['Robotics', 'C++', 'Python', 'ROS'], good_to_have_skills: ['Electronics', 'Control Systems'], status: 'approved' },
  { id: 40, title: 'Geographic Information System (GIS) Intern', company_name: 'GeoSpatial Analytics', location: 'Hyderabad, Telangana', work_mode: 'Hybrid', deadline: '2025-11-19T23:59:59Z', start_date: '2025-12-03T09:00:00Z', description: 'Assist with spatial data analysis, map creation, and developing GIS applications.', must_have_skills: ['GIS Software (ArcGIS/QGIS)', 'Data Analysis', 'Cartography'], good_to_have_skills: ['Python Scripting', 'Remote Sensing'], status: 'approved' },
  { id: 41, title: 'Actuarial Intern', company_name: 'Risk Assess Insure', location: 'Mumbai, Maharashtra', work_mode: 'Hybrid', deadline: '2025-12-01T23:59:59Z', start_date: '2025-12-15T09:00:00Z', description: 'Support actuaries in analyzing financial costs of risk and uncertainty using math and stats.', must_have_skills: ['Statistics', 'MS Excel', 'Probability Theory'], good_to_have_skills: ['SQL', 'VBA', 'Actuarial Exams'], status: 'approved' },
  { id: 42, title: 'Food Technology Intern', company_name: 'Nourish Foods', location: 'Kochi, Kerala', work_mode: 'On-site', deadline: '2025-11-25T23:59:59Z', start_date: '2025-12-10T09:00:00Z', description: 'Work in the R&D lab on new product development, quality analysis, and sensory evaluation.', must_have_skills: ['Food Science', 'Quality Control', 'Lab Practices'], good_to_have_skills: ['Sensory Analysis', 'Food Safety'], status: 'approved' },
  { id: 43, title: 'Renewable Energy Intern', company_name: 'SolarWind Power', location: 'Jaipur, Rajasthan', work_mode: 'Hybrid', deadline: '2025-11-20T23:59:59Z', start_date: '2025-12-05T09:00:00Z', description: 'Assist engineers with solar or wind farm project analysis, site assessment, and performance monitoring.', must_have_skills: ['Renewable Energy', 'Data Analysis', 'MS Excel'], good_to_have_skills: ['AutoCAD', 'PVsyst'], status: 'approved' },
  { id: 44, title: 'Public Relations Intern', company_name: 'Media Connect PR', location: 'Delhi', work_mode: 'Hybrid', deadline: '2025-11-30T23:59:59Z', start_date: '2025-12-15T09:00:00Z', description: 'Support PR campaigns by drafting press releases, monitoring media coverage, and building media lists.', must_have_skills: ['Public Relations', 'Writing', 'Media Relations'], good_to_have_skills: ['Social Media', 'Cision'], status: 'approved' },
  { id: 45, title: 'Film Production Intern', company_name: 'CinemaScope Pictures', location: 'Mumbai, Maharashtra', work_mode: 'On-site', deadline: '2025-12-10T23:59:59Z', start_date: '2026-01-05T09:00:00Z', description: 'Gain on-set experience by assisting various departments like direction, camera, or art.', must_have_skills: ['Film Production Basics', 'Teamwork', 'Adaptability'], good_to_have_skills: ['Screenwriting', 'Editing Software'], status: 'approved' },
  { id: 46, title: 'Game Development Intern', company_name: 'Level Up Studios', location: 'Bengaluru, Karnataka', work_mode: 'Remote', deadline: '2025-12-20T23:59:59Z', start_date: '2026-01-10T09:00:00Z', description: 'Assist in the design and development of video games using engines like Unity or Unreal.', must_have_skills: ['Game Development', 'Unity or Unreal Engine', 'C# or C++'], good_to_have_skills: ['3D Modeling', 'Game Design Principles'], status: 'approved' },
  { id: 47, title: 'Library Science Intern', company_name: 'City Central Library', location: 'Kolkata, West Bengal', work_mode: 'On-site', deadline: '2025-11-20T23:59:59Z', start_date: '2025-12-05T09:00:00Z', description: 'Learn about library operations, including cataloging, reference services, and digital archives.', must_have_skills: ['Cataloging', 'Information Retrieval', 'Organization'], good_to_have_skills: ['Library Management Software', 'Digital Archiving'], status: 'approved' },
  { id: 48, title: 'Social Work Intern', company_name: 'Hope Foundation NGO', location: 'Chennai, Tamil Nadu', work_mode: 'On-site', deadline: '2025-11-15T23:59:59Z', start_date: '2025-12-01T09:00:00Z', description: 'Engage in community outreach programs, assist with counseling sessions, and support case management.', must_have_skills: ['Social Work Principles', 'Empathy', 'Communication'], good_to_have_skills: ['Case Management', 'Community Outreach'], status: 'approved' },
  { id: 49, title: 'Materials Science Intern', company_name: 'NanoMaterials Tech', location: 'Pune, Maharashtra', work_mode: 'On-site', deadline: '2025-12-01T23:59:59Z', start_date: '2025-12-15T09:00:00Z', description: 'Work in a lab setting to characterize and test new materials, focusing on polymers or composites.', must_have_skills: ['Materials Science', 'Lab Testing', 'Characterization'], good_to_have_skills: ['SEM/TEM', 'Composites'], status: 'approved' },
  { id: 50, title: 'Sports Management Intern', company_name: 'ProLeagues Sports', location: 'Delhi', work_mode: 'Hybrid', deadline: '2025-11-25T23:59:59Z', start_date: '2025-12-10T09:00:00Z', description: 'Assist with team operations, event logistics, and sports marketing campaigns.', must_have_skills: ['Sports Management', 'Event Coordination', 'Marketing'], good_to_have_skills: ['Sponsorships', 'Team Logistics'], status: 'approved' },
];